import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import { vitePrerenderPlugin } from 'vite-prerender-plugin'
import path from 'node:path'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Import generated routes file (created by prebuild script)
// Fallback to static routes if routes.json doesn't exist
function getStaticRoutes() {
  return [
    '/',
    '/services',
    '/products',
    '/academy',
    '/industries',
    '/hire-developers',
    '/hire-talent',
    '/partner-success',
    '/case-studies',
    '/press-releases',
    '/articles',
    '/webinars',
    '/videos',
    '/resources',
    '/about',
    '/company',
    '/contact',
    '/career',
    '/careers',
    '/brand-guidelines',
    '/BrandGuidelines',
    '/privacy-policy',
    '/terms-conditions',
  ]
}

let allRoutes = []
try {
  const routesFile = join(__dirname, 'routes.json')
  const routesData = readFileSync(routesFile, 'utf-8')
  allRoutes = JSON.parse(routesData)
  console.log(`✅ Loaded ${allRoutes.length} routes from routes.json`)
} catch (error) {
  console.warn('⚠️  Could not load routes.json, using static routes only:', error.message)
  // Fallback to static routes
  allRoutes = getStaticRoutes()
}

// Routes are pre-generated by prebuild script. Optional: VITE_STRAPI_PROXY_TARGET in .env for hosted Strapi.
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, __dirname, '')
  const strapiProxyTarget =
    (env.VITE_STRAPI_PROXY_TARGET || 'http://localhost:1337').replace(/\/$/, '')

  if (env.VITE_STRAPI_PROXY_TARGET) {
    console.log(`[vite] Proxy /api → ${strapiProxyTarget} (hosted Strapi)`)
  }

  return {
    plugins: [
      react(),
      vitePrerenderPlugin({
        renderTarget: '#root', // MUST match your React mount element
        prerenderScript: path.resolve('src/prerender.jsx'), // Explicitly point to prerender function
        additionalPrerenderRoutes: allRoutes, // Use pre-generated routes (static + dynamic from Strapi)
      }),
    ],
    server: {
      port: 3000,
      proxy: {
        '/api': {
          target: strapiProxyTarget,
          changeOrigin: true,
          // Forward browser Origin so Strapi (and custom CORS middleware) see http://localhost:3000
          configure(proxy) {
            proxy.on('proxyReq', (proxyReq, req) => {
              const origin = req.headers.origin
              if (origin) {
                proxyReq.setHeader('Origin', origin)
              }
            })
          },
        },
      },
    },
  }
})
