import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import vitePrerenderPlugin from 'vite-prerender-plugin'
import path from 'node:path'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Import generated routes file (created by prebuild script)
let allRoutes = []
try {
  const routesFile = join(__dirname, 'routes.json')
  const routesData = readFileSync(routesFile, 'utf-8')
  allRoutes = JSON.parse(routesData)
  console.log(`✅ Loaded ${allRoutes.length} routes from routes.json`)
} catch (error) {
  console.warn('⚠️  Could not load routes.json, using static routes only:', error.message)
  // Fallback to basic static routes
  allRoutes = ['/']
}

// Synchronous Vite config - routes are pre-generated by prebuild script
export default defineConfig({
  plugins: [
    react(),
    vitePrerenderPlugin({
      renderTarget: '#root', // MUST match your React mount element
      prerenderScript: path.resolve('src/prerender.jsx'), // Explicitly point to prerender function
      additionalPrerenderRoutes: allRoutes, // Use pre-generated routes (static + dynamic from Strapi)
    }),
  ],
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:1337',
        changeOrigin: true,
      },
    },
  },
})
